# Let Spring Boot 3 automatically parse the Railway DATABASE_URL
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis Configuration (Railway uses REDISHOST and REDISPORT by default)
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT:6379}
spring.data.redis.password=${REDISPASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Custom property for your logic
app.base-url=https://url-shortner-using-spring-boot-production.up.railway.app